"use client";
import {useEffect,useState} from "react";
import DemoSection from "./demo-section";
import AboutSection from "./about-section";
type Lang="pt"|"en";
const copy={
pt:{nav:["Projetos","Serviços","Sobre","Contato"],eye:"Relacionamento com clientes · São Paulo",a:"Conexões. Ideias.",b:"Resultados.",lead:"Aproximo empresas de soluções digitais que transformam ideias em oportunidades reais.",start:"Falar com Linda",view:"Conhecer meu trabalho",sk:"Como posso ajudar",st:"Da primeira conversa a uma parceria de confiança.",scopeTitle:"Comunicação que conecta negócios e tecnologia.",scope:"Atuo no relacionamento com clientes da AmeerTrc, compreendendo necessidades, apresentando soluções digitais e acompanhando cada contato com clareza, atenção e profissionalismo.",cards:[["Atendimento a clientes","Escuto cada cliente e entendo seus objetivos, desafios e prioridades."],["Apresentação de soluções","Apresento sites, aplicativos e possibilidades digitais de forma clara e acessível."],["Desenvolvimento de negócios","Identifico oportunidades e ajudo empresas a fortalecer sua presença digital."],["Organização de reuniões","Coordeno conversas e reuniões entre clientes e a equipe de desenvolvimento."],["Acompanhamento de projetos","Mantenho uma comunicação próxima durante as etapas comerciais do projeto."],["Conexão com a AmeerTrc","Faço a ponte entre cada negócio e as soluções desenvolvidas pela AmeerTrc."]],work:"Projetos que represento",projects:[["Lomraxe.com","Produto digital completo desenvolvido e lançado na web.","Website"],["Lomraxe","Aplicativo publicado oficialmente no Google Play.","Google Play"]],built:["Criado para","a web."],available:["Disponível no","Google Play."],ak:"Sobre mim",at:"Pessoas primeiro. Negócios com propósito.",ap:"Sou Linda Lisa, Assistente de Desenvolvimento de Negócios e Relacionamento com Clientes na AmeerTrc. Ajudo empresas e profissionais a entender como sites, aplicativos e soluções digitais podem fortalecer seus negócios. Meu trabalho é ouvir cada cliente, apresentar as melhores possibilidades e apoiar a comunicação em todas as etapas do projeto.",process:"Comunicação · Planejamento · Relacionamento · Acompanhamento",ck:"Vamos conversar?",ct:"Sua próxima ideia pode começar aqui.",cp:"Conte-me sobre seu negócio e conectarei você às melhores possibilidades digitais com a AmeerTrc.",ig:"Instagram",wa:"WhatsApp",open:"Ver projeto",foot:"Relacionamento com clientes & desenvolvimento de negócios."},
en:{nav:["Work","Services","About","Contact"],eye:"Client relations · São Paulo",a:"Connections. Ideas.",b:"Results.",lead:"I connect businesses with digital solutions that turn ideas into real opportunities.",start:"Talk to Linda",view:"Explore my work",sk:"How I can help",st:"From the first conversation to a trusted partnership.",scopeTitle:"Communication that connects business and technology.",scope:"I support client relations at AmeerTrc by understanding needs, presenting digital solutions and guiding every conversation with clarity, care and professionalism.",cards:[["Client Relations","I listen to every client and understand their goals, challenges and priorities."],["Solution Presentation","I present websites, applications and digital possibilities in a clear and accessible way."],["Business Development","I identify opportunities and help businesses strengthen their digital presence."],["Meeting Coordination","I organize conversations and meetings between clients and the development team."],["Project Follow-up","I maintain close communication throughout the commercial stages of each project."],["AmeerTrc Connection","I connect each business with the right solutions developed by AmeerTrc."]],work:"Projects I represent",projects:[["Lomraxe.com","A complete digital product developed and launched on the web.","Website"],["Lomraxe","A mobile application officially published on Google Play.","Google Play"]],built:["Built for","the web."],available:["Available on","Google Play."],ak:"About me",at:"People first. Business with purpose.",ap:"I’m Linda Lisa, a Business Development and Client Relations Assistant at AmeerTrc. I help businesses and professionals understand how websites, applications and digital solutions can strengthen their operations. My role is to listen to each client, present the best possibilities and support communication throughout every stage of the project.",process:"Communication · Planning · Client Relations · Support",ck:"Let’s talk?",ct:"Your next idea can start here.",cp:"Tell me about your business and I will connect you with the best digital possibilities at AmeerTrc.",ig:"Instagram",wa:"WhatsApp",open:"View project",foot:"Client relations & business development."}}
const Arrow=()=> <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M5 12h14M13 6l6 6-6 6"/></svg>;
const Ig=()=> <svg aria-hidden="true" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor"/></svg>;
const Wa=()=> <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M20 11.7a8 8 0 0 1-11.9 7L4 20l1.3-4A8 8 0 1 1 20 11.7Z"/><path d="M9 8c.3 3 2 4.7 5 5l1-1.3 2 .9c-.2 1.7-1.4 2.5-3 2.4-3.8-.4-6.6-3.2-7-7 0-1.6.8-2.8 2.4-3l.9 2L9 8Z"/></svg>;
export default function Home({initialLang="pt"}:{initialLang?:Lang}){const[l]=useState<Lang>(initialLang),t=copy[l];useEffect(()=>{document.documentElement.lang=l==="pt"?"pt-BR":"en"},[l]);return <main>
<header><a className="logo" href="#top"><span>Linda</span><b>Trc</b></a><nav>{t.nav.map((n,i)=><a key={n} href={["#work","#services","#about","#contact"][i]}>{n}</a>)}</nav><div className="tools"><div className="langs"><a href="/pt" aria-current={l==="pt"?"page":undefined}>PT</a><a href="/en" aria-current={l==="en"?"page":undefined}>EN</a></div><a className="instagram" href="https://www.instagram.com/ameer_trc" target="_blank" rel="noreferrer" aria-label="Instagram"><Ig/></a><a className="green" href="https://wa.me/5511988180530" target="_blank" rel="noreferrer" aria-label="WhatsApp"><Wa/></a></div></header>
<section className="hero" id="top"><div className="glow"/><div className="hero-copy"><p className="kicker">{t.eye}</p><h1><span>{t.a}</span><em>{t.b}</em></h1><p className="lead">{t.lead}</p><div className="actions"><a className="btn primary" href="https://wa.me/5511988180530" target="_blank"><Wa/>{t.start}</a><a className="btn outline" href="#work">{t.view}<Arrow/></a></div></div><div className="art" aria-hidden="true"><div className="portrait-card"><span>CLIENT RELATIONS</span><b>LL</b><i>Linda Lisa</i></div></div></section>
<section className="section services" id="services"><div className="heading"><div><p className="kicker">{t.sk}</p><h2>{t.st}</h2></div><span>01 — 06</span></div><div className="business-scope"><h3>{t.scopeTitle}</h3><p>{t.scope}</p></div><div className="card-grid">{t.cards.map((c,i)=><article className="service-card" key={c[0]}><div className={"symbol s"+i}/><small>0{i+1}</small><h3>{c[0]}</h3><p>{c[1]}</p></article>)}</div></section>
<section className="section work" id="work"><div className="work-head"><h2>{t.work}</h2><i/></div><div className="project-grid">{t.projects.map((p,i)=>{const url=i===0?"https://lomraxe.com":"https://play.google.com/store/apps/details?id=com.amorabr.app",label=i===0?t.built:t.available;return <a className={"project p"+i} key={p[0]} href={url} target="_blank"><div className="project-art"><b className={i===0?"lomraxe":"amora"}>LOMRAXE</b><strong>{label[0]}<br/>{label[1]}</strong></div><div className="project-copy"><span>{p[2]}</span><h3>{p[0]}</h3><p>{p[1]}</p><b className="project-link">{t.open}<Arrow/></b></div></a>})}</div></section>
<DemoSection lang={l}/>
<AboutSection lang={l}/>
<section className="section contact" id="contact"><p className="kicker">{t.ck}</p><h2>{t.ct}</h2><p>{t.cp}</p><div className="actions center"><a className="btn primary" href="https://wa.me/5511988180530" target="_blank"><Wa/>{t.wa}</a><a className="btn outline" href="https://www.instagram.com/ameer_trc" target="_blank"><Ig/>{t.ig}</a></div><a className="phone" href="tel:+5511988180530">+55 (11) 98818-0530</a></section>
<footer><a className="logo" href="#top"><span>Linda</span><b>Trc</b></a><p>{t.foot}</p><span>© 2026 LindaLisa · AmeerTrc</span></footer></main>}
